### PR TITLE
Re-generate CLDF, update metdata, update code

### PR DESCRIPTION
**Pull request by chrzyki**

### CODE REVIEW

**Comment by LinguList** [comment]
Please merge, without PR, I cannot review all of them now. We review
when finalizing, not during this stage.

**Comment by chrzyki** [comment]
I requested a review from @Bibiko because he has extensively worked on the data in the past and I didn't want to push without notifying him.

**Comment by LinguList** [comment]
Ah sorry... I am overwhelmed by github issues these days...

**Comment by chrzyki** [comment]
No worries, there's a lot going on. :) I'll do the other Lexibank updates without PRs.

**Review by Bibiko — APPROVED** [review]

**Pull request merged**
